"""DynamoDB Stack for MediaContracts.

Table: contract_review_jobs
  PK  job_id     (String) — uuid generated by caller, idempotency key
  SK  specialist (String) — 'orchestrator' | 'financial' | 'rights_clearance' |
                             'talent_guild_compliance' | 'regulatory_compliance' |
                             'risk_strategist' | 'summary'

Attributes (written by each runtime):
  status        : PENDING | RUNNING | COMPLETE | FAILED
  result_s3_key : S3 key where XML output was written
  started_at    : ISO-8601 timestamp
  completed_at  : ISO-8601 timestamp
  error         : error message (FAILED only)
  retry_count   : int (0-3)

GSI: status-index
  PK  status     — allows querying all jobs in a given state (ops/monitoring)
  SK  started_at
"""

from aws_cdk import (
    Duration,
    RemovalPolicy,
    Stack,
    Tags,
    CfnOutput,
    aws_dynamodb as dynamodb,
    aws_ssm as ssm,
)
from constructs import Construct


class DynamoDBStack(Stack):
    """DynamoDB table for job state and checkpointing."""

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        deployment_id: str,
        stack_suffix: str,
        deployment_tags: dict[str, str],
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        self.deployment_id = deployment_id
        self.deployment_tags = deployment_tags
        self._apply_common_tags()

        # ── Jobs table ─────────────────────────────────────────────
        self.jobs_table = dynamodb.Table(
            self,
            "ContractReviewJobs",
            table_name=f"media-contracts-jobs-{deployment_id}-{stack_suffix}",
            partition_key=dynamodb.Attribute(
                name="job_id",
                type=dynamodb.AttributeType.STRING,
            ),
            sort_key=dynamodb.Attribute(
                name="specialist",
                type=dynamodb.AttributeType.STRING,
            ),
            billing_mode=dynamodb.BillingMode.PAY_PER_REQUEST,
            point_in_time_recovery_specification=dynamodb.PointInTimeRecoverySpecification(
                point_in_time_recovery_enabled=True,
            ),
            encryption=dynamodb.TableEncryption.AWS_MANAGED,
            removal_policy=RemovalPolicy.DESTROY,
            # TTL: auto-expire job records after 30 days
            time_to_live_attribute="ttl",
        )

        # GSI for ops monitoring — query by status
        self.jobs_table.add_global_secondary_index(
            index_name="status-index",
            partition_key=dynamodb.Attribute(
                name="status",
                type=dynamodb.AttributeType.STRING,
            ),
            sort_key=dynamodb.Attribute(
                name="started_at",
                type=dynamodb.AttributeType.STRING,
            ),
            projection_type=dynamodb.ProjectionType.INCLUDE,
            non_key_attributes=["job_id", "specialist", "result_s3_key", "error"],
        )

        # ── SSM parameter for runtime discovery ────────────────────
        ssm.StringParameter(
            self,
            "JobsTableParam",
            parameter_name=f"/mc-{stack_suffix}/jobs-table-name",
            string_value=self.jobs_table.table_name,
            description="DynamoDB jobs table name",
        )

        # ── Outputs ────────────────────────────────────────────────
        CfnOutput(
            self,
            "JobsTableName",
            value=self.jobs_table.table_name,
            export_name=f"{self.stack_name}-JobsTableName",
        )
        CfnOutput(
            self,
            "JobsTableArn",
            value=self.jobs_table.table_arn,
            export_name=f"{self.stack_name}-JobsTableArn",
        )

    def _apply_common_tags(self) -> None:
        for k, v in self.deployment_tags.items():
            Tags.of(self).add(k, v)
