#!/usr/bin/env python3
"""MediaContracts CDK App.

Stack deployment order:
  1.  MediaContractsVpc               — VPC, subnets, VPC endpoints
  2.  MediaContractsCognito            — User pool, UI client, Gateway M2M client
  3.  MediaContractsInferenceProfiles  — Bedrock Application Inference Profiles
  4.  MediaContractsS3                 — config / source / results buckets
  5.  MediaContractsDynamoDB           — jobs table with status GSI
  6.  MediaContractsECR                — ECR repo for orchestrator container
  7.  MediaContractsIAM                — orchestrator execution role
  8.  MediaContracts-AnalysisKB         — Bedrock KB (S3 Vectors backend)
  9.  MediaContractsSpecialists        — specialist Lambda functions
  10. MediaContractsGateway            — AgentCore Gateway (MCP, specialist tools)
  11. MediaContractsRuntimes           — orchestrator AgentCore Runtime
  12. MediaContractsXRay               — X-Ray Transaction Search enablement
  13. MediaContractsDashboard          — CloudWatch operational dashboard
  14. MediaContractsECS                — ECS task definition (SSM-backed config)

Each stack name gets a 3-character suffix (STACK_SUFFIX env var) so you can
spin up parallel environments without waiting for teardown.  The suffix is
auto-generated by deploy.sh and persisted in .deploy-state-{DEPLOYMENT_ID}.json.

Two-phase deploy — Gateway URL is only known after stack 10 deploys:

  Phase 1 (stacks 1-10):
    DEPLOYMENT_ID=dev STACK_SUFFIX=a1b cdk deploy MC-Vpc-a1b MC-Cognito-a1b ...

  Phase 2 (after getting Gateway URL from stack 10 outputs):
    GATEWAY_URL=https://... DEPLOYMENT_ID=dev STACK_SUFFIX=a1b cdk deploy ...
"""

import os
import secrets
import aws_cdk as cdk

from stacks.auto_trigger_stack import AutoTriggerStack
from stacks.agentcore_runtimes_stack import AgentCoreRuntimesStack
from stacks.cognito_stack import CognitoStack
from stacks.dashboard_stack import DashboardStack
from stacks.dynamodb_stack import DynamoDBStack
from stacks.ecr_stack import ECRStack
from stacks.ecs_stack import ECSStack
from stacks.gateway_stack import GatewayStack
from stacks.iam_stack import IAMStack
from stacks.inference_profiles_stack import InferenceProfilesStack
from stacks.kb_sync_stack import KBSyncStack
from stacks.knowledge_base_stack import KnowledgeBaseStack
from stacks.s3_stack import S3Stack
from stacks.specialist_lambdas_stack import SpecialistLambdasStack
from stacks.terms_kb_stack import TermsKBStack
from stacks.vpc_stack import VpcStack
from stacks.xray_stack import XRayStack

# ── Deployment configuration ───────────────────────────────────────────────
DEPLOYMENT_ID = os.environ.get("DEPLOYMENT_ID", "dev")
STACK_SUFFIX = os.environ.get("STACK_SUFFIX", secrets.token_hex(2)[:3])
AWS_REGION = os.environ.get("CDK_DEFAULT_REGION", "us-west-2")
AWS_ACCOUNT = os.environ.get("CDK_DEFAULT_ACCOUNT")
IMAGE_TAG = os.environ.get("IMAGE_TAG", "latest")
MODEL_ID = os.environ.get("MODEL_ID", "us.anthropic.claude-sonnet-4-6")


def _sid(name: str) -> str:
    """Build a stack construct ID with the unique suffix, e.g. MC-Vpc-a1b."""
    return f"MC-{name}-{STACK_SUFFIX}"


# Phase 2 only — set after Gateway deploys
GATEWAY_URL = os.environ.get("GATEWAY_URL", "")

# CORS origin for S3 presigned uploads — set to ECS service endpoint after first deploy
CORS_ORIGIN = os.environ.get("CORS_ORIGIN", "")

# UI callback URL — update to ECS ALB URL before building the UI image
UI_CALLBACK_URL = os.environ.get("UI_CALLBACK_URL", "http://localhost:7870/callback")
UI_LOGOUT_URL = os.environ.get("UI_LOGOUT_URL", "http://localhost:7870/")
UI_PUBLIC_ACCESS = os.environ.get("UI_PUBLIC_ACCESS", "true").lower() == "true"

DEPLOYMENT_TAGS = {
    "project": "media-contracts",
    "deployment_id": DEPLOYMENT_ID,
    "managed_by": "cdk",
}

env = cdk.Environment(account=AWS_ACCOUNT, region=AWS_REGION)
app = cdk.App()

# ── 1: VPC ─────────────────────────────────────────────────────────────────
vpc_stack = VpcStack(
    app,
    _sid("Vpc"),
    deployment_id=DEPLOYMENT_ID,
    stack_suffix=STACK_SUFFIX,
    deployment_tags=DEPLOYMENT_TAGS,
    env=env,
)

# ── 2: Cognito ─────────────────────────────────────────────────────────────
cognito_stack = CognitoStack(
    app,
    _sid("Cognito"),
    deployment_id=DEPLOYMENT_ID,
    stack_suffix=STACK_SUFFIX,
    deployment_tags=DEPLOYMENT_TAGS,
    ui_callback_url=UI_CALLBACK_URL,
    ui_logout_url=UI_LOGOUT_URL,
    env=env,
)

# ── 3: Inference Profiles ──────────────────────────────────────────────────
inference_profiles_stack = InferenceProfilesStack(
    app,
    _sid("InferenceProfiles"),
    deployment_id=DEPLOYMENT_ID,
    stack_suffix=STACK_SUFFIX,
    deployment_tags=DEPLOYMENT_TAGS,
    env=env,
)

# ── 4: S3 ──────────────────────────────────────────────────────────────────
s3_stack = S3Stack(
    app,
    _sid("S3"),
    deployment_id=DEPLOYMENT_ID,
    stack_suffix=STACK_SUFFIX,
    deployment_tags=DEPLOYMENT_TAGS,
    cors_origin=CORS_ORIGIN,
    env=env,
)

# ── 5: DynamoDB ────────────────────────────────────────────────────────────
dynamodb_stack = DynamoDBStack(
    app,
    _sid("DynamoDB"),
    deployment_id=DEPLOYMENT_ID,
    stack_suffix=STACK_SUFFIX,
    deployment_tags=DEPLOYMENT_TAGS,
    env=env,
)

# ── 6: ECR ─────────────────────────────────────────────────────────────────
ecr_stack = ECRStack(
    app,
    _sid("ECR"),
    deployment_id=DEPLOYMENT_ID,
    stack_suffix=STACK_SUFFIX,
    deployment_tags=DEPLOYMENT_TAGS,
    env=env,
)

# ── 7: IAM ─────────────────────────────────────────────────────────────────
iam_stack = IAMStack(
    app,
    _sid("IAM"),
    deployment_id=DEPLOYMENT_ID,
    stack_suffix=STACK_SUFFIX,
    deployment_tags=DEPLOYMENT_TAGS,
    config_bucket=s3_stack.config_bucket,
    source_bucket=s3_stack.source_bucket,
    results_bucket=s3_stack.results_bucket,
    jobs_table=dynamodb_stack.jobs_table,
    kms_key_arn=s3_stack.kms_key.key_arn,
    env=env,
)
iam_stack.add_dependency(s3_stack)
iam_stack.add_dependency(dynamodb_stack)

# Grant orchestrator role invoke permissions on application inference profiles
inference_profiles_stack.grant_invoke_to_role(iam_stack.orchestrator_role)
iam_stack.add_dependency(inference_profiles_stack)

# ── 8: Knowledge Base ──────────────────────────────────────────────────────
kb_stack = KnowledgeBaseStack(
    app,
    _sid("AnalysisKB"),
    deployment_id=DEPLOYMENT_ID,
    stack_suffix=STACK_SUFFIX,
    deployment_tags=DEPLOYMENT_TAGS,
    results_bucket=s3_stack.results_bucket,
    kms_key_arn=s3_stack.kms_key.key_arn,
    env=env,
)
kb_stack.add_dependency(s3_stack)

# ── 8b: Terms Knowledge Base ──────────────────────────────────────────────
terms_kb_stack = TermsKBStack(
    app,
    _sid("TermsKB"),
    deployment_id=DEPLOYMENT_ID,
    stack_suffix=STACK_SUFFIX,
    deployment_tags=DEPLOYMENT_TAGS,
    terms_bucket=s3_stack.terms_bucket,
    kms_key_arn=s3_stack.kms_key.key_arn,
    env=env,
)
terms_kb_stack.add_dependency(s3_stack)

# ── 9: Specialist Lambdas ──────────────────────────────────────────────────
specialist_lambdas_stack = SpecialistLambdasStack(
    app,
    _sid("Specialists"),
    deployment_id=DEPLOYMENT_ID,
    stack_suffix=STACK_SUFFIX,
    deployment_tags=DEPLOYMENT_TAGS,
    config_bucket=s3_stack.config_bucket,
    results_bucket=s3_stack.results_bucket,
    jobs_table=dynamodb_stack.jobs_table,
    kms_key_arn=s3_stack.kms_key.key_arn,
    glossary_kb_id=terms_kb_stack.knowledge_base.attr_knowledge_base_id,
    model_id=MODEL_ID,
    sonnet_46_profile_arn=inference_profiles_stack.sonnet_46_arn,
    opus_46_profile_arn=inference_profiles_stack.opus_46_arn,
    sonnet_45_profile_arn=inference_profiles_stack.sonnet_45_arn,
    haiku_45_profile_arn=inference_profiles_stack.haiku_45_arn,
    env=env,
)
specialist_lambdas_stack.add_dependency(s3_stack)
specialist_lambdas_stack.add_dependency(dynamodb_stack)
specialist_lambdas_stack.add_dependency(inference_profiles_stack)
specialist_lambdas_stack.add_dependency(terms_kb_stack)

# ── 10: Gateway ────────────────────────────────────────────────────────────
# Cognito user pool + gateway client wired directly from cognito_stack
gateway_stack = GatewayStack(
    app,
    _sid("Gateway"),
    deployment_id=DEPLOYMENT_ID,
    stack_suffix=STACK_SUFFIX,
    deployment_tags=DEPLOYMENT_TAGS,
    specialist_lambdas=specialist_lambdas_stack.functions,
    config_bucket=s3_stack.config_bucket,
    cognito_user_pool_id=cognito_stack.user_pool.user_pool_id,
    cognito_client_id=cognito_stack.gateway_client.user_pool_client_id,
    env=env,
)
gateway_stack.add_dependency(specialist_lambdas_stack)
gateway_stack.add_dependency(cognito_stack)

# ── 11: X-Ray Transaction Search (must be enabled before runtimes) ─────────
xray_stack = XRayStack(
    app,
    _sid("XRay"),
    deployment_id=DEPLOYMENT_ID,
    stack_suffix=STACK_SUFFIX,
    deployment_tags=DEPLOYMENT_TAGS,
    env=env,
)

# ── 12: Orchestrator Runtime ───────────────────────────────────────────────
# GATEWAY_URL must be set from stack 10 outputs before deploying this stack.
# Cognito gateway secret ARN comes directly from cognito_stack.
private_subnet_ids = [s.subnet_id for s in vpc_stack.vpc.private_subnets]
public_subnet_ids = [s.subnet_id for s in vpc_stack.vpc.public_subnets]

runtimes_stack = AgentCoreRuntimesStack(
    app,
    _sid("Runtimes"),
    deployment_id=DEPLOYMENT_ID,
    stack_suffix=STACK_SUFFIX,
    deployment_tags=DEPLOYMENT_TAGS,
    orchestrator_ecr_uri=ecr_stack.repositories["orchestrator"].repository_uri,
    orchestrator_role=iam_stack.orchestrator_role,
    kms_key=s3_stack.kms_key,
    config_bucket_name=s3_stack.config_bucket.bucket_name,
    results_bucket_name=s3_stack.results_bucket.bucket_name,
    source_bucket_name=s3_stack.source_bucket.bucket_name,
    jobs_table_name=dynamodb_stack.jobs_table.table_name,
    gateway_url=GATEWAY_URL,
    cognito_secret_arn=cognito_stack.gateway_secret.secret_arn,
    cognito_gateway_client_id=cognito_stack.gateway_client.user_pool_client_id,
    cognito_token_endpoint=f"https://media-contracts-{DEPLOYMENT_ID}-{STACK_SUFFIX}.auth.{AWS_REGION}.amazoncognito.com/oauth2/token",
    private_subnet_ids=private_subnet_ids,
    runtime_sg_id=vpc_stack.runtime_sg.security_group_id,
    model_id=MODEL_ID,
    image_tag=IMAGE_TAG,
    sonnet_46_profile_arn=inference_profiles_stack.sonnet_46_arn,
    opus_46_profile_arn=inference_profiles_stack.opus_46_arn,
    sonnet_45_profile_arn=inference_profiles_stack.sonnet_45_arn,
    haiku_45_profile_arn=inference_profiles_stack.haiku_45_arn,
    env=env,
)
runtimes_stack.add_dependency(iam_stack)
runtimes_stack.add_dependency(ecr_stack)
runtimes_stack.add_dependency(vpc_stack)
runtimes_stack.add_dependency(gateway_stack)
runtimes_stack.add_dependency(cognito_stack)
runtimes_stack.add_dependency(inference_profiles_stack)
runtimes_stack.add_dependency(xray_stack)

# ── 11b: Auto-trigger (pipeline/ prefix → Lambda → Runtime) ───────
auto_trigger_stack = AutoTriggerStack(
    app,
    _sid("AutoTrigger"),
    deployment_id=DEPLOYMENT_ID,
    stack_suffix=STACK_SUFFIX,
    deployment_tags=DEPLOYMENT_TAGS,
    source_bucket_name=s3_stack.source_bucket.bucket_name,
    source_bucket_arn=s3_stack.source_bucket.bucket_arn,
    jobs_table=dynamodb_stack.jobs_table,
    orchestrator_runtime_arn=runtimes_stack.orchestrator_runtime.attr_agent_runtime_arn,
    kms_key_arn=s3_stack.kms_key.key_arn,
    env=env,
)
auto_trigger_stack.add_dependency(runtimes_stack)
auto_trigger_stack.add_dependency(s3_stack)
auto_trigger_stack.add_dependency(dynamodb_stack)

# ── 11c: KB Sync (S3 events → Lambda → StartIngestionJob) ────────
kb_sync_stack = KBSyncStack(
    app,
    _sid("AnalysisKBSync"),
    deployment_id=DEPLOYMENT_ID,
    stack_suffix=STACK_SUFFIX,
    deployment_tags=DEPLOYMENT_TAGS,
    results_bucket_name=s3_stack.results_bucket.bucket_name,
    results_bucket_arn=s3_stack.results_bucket.bucket_arn,
    terms_bucket_name=s3_stack.terms_bucket.bucket_name,
    terms_bucket_arn=s3_stack.terms_bucket.bucket_arn,
    contract_kb_id=kb_stack.knowledge_base.attr_knowledge_base_id,
    contract_datasource_id=kb_stack.data_source.attr_data_source_id,
    terms_kb_id=terms_kb_stack.knowledge_base.attr_knowledge_base_id,
    terms_datasource_id=terms_kb_stack.data_source.attr_data_source_id,
    kms_key_arn=s3_stack.kms_key.key_arn,
    env=env,
)
kb_sync_stack.add_dependency(kb_stack)
kb_sync_stack.add_dependency(terms_kb_stack)
kb_sync_stack.add_dependency(s3_stack)

# ── 13: Dashboard ──────────────────────────────────────────────────────────
dashboard_stack = DashboardStack(
    app,
    _sid("Dashboard"),
    deployment_id=DEPLOYMENT_ID,
    stack_suffix=STACK_SUFFIX,
    deployment_tags=DEPLOYMENT_TAGS,
    specialist_lambdas=specialist_lambdas_stack.functions,
    jobs_table_name=dynamodb_stack.jobs_table.table_name,
    orchestrator_runtime_id=runtimes_stack.orchestrator_runtime.attr_agent_runtime_id,
    orchestrator_log_group=runtimes_stack.app_log_group,
    gateway=gateway_stack.gateway,
    gateway_log_group=gateway_stack.gateway_log_group,
    env=env,
)
dashboard_stack.add_dependency(specialist_lambdas_stack)
dashboard_stack.add_dependency(runtimes_stack)
dashboard_stack.add_dependency(gateway_stack)

# ── 14: ECS Task Definition ────────────────────────────────────────────────
# Depends on runtimes (orchestrator ARN in SSM) and cognito (SSM params).
# Build the UI image AFTER running generate_ui_env.sh to bake Cognito config.
ecs_stack = ECSStack(
    app,
    _sid("ECS"),
    deployment_id=DEPLOYMENT_ID,
    stack_suffix=STACK_SUFFIX,
    deployment_tags=DEPLOYMENT_TAGS,
    config_bucket_arn=s3_stack.config_bucket.bucket_arn,
    results_bucket_arn=s3_stack.results_bucket.bucket_arn,
    source_bucket_arn=s3_stack.source_bucket.bucket_arn,
    jobs_table_arn=dynamodb_stack.jobs_table.table_arn,
    kms_key_arn=s3_stack.kms_key.key_arn,
    private_subnet_ids=public_subnet_ids if UI_PUBLIC_ACCESS else private_subnet_ids,
    ui_task_sg_id=vpc_stack.ui_task_sg.security_group_id,
    cognito_user_pool_id=cognito_stack.user_pool.user_pool_id,
    cognito_ui_client_id=cognito_stack.ui_client.user_pool_client_id,
    image_tag=IMAGE_TAG,
    chat_model=MODEL_ID,
    env=env,
)
ecs_stack.add_dependency(s3_stack)
ecs_stack.add_dependency(dynamodb_stack)
ecs_stack.add_dependency(runtimes_stack)
ecs_stack.add_dependency(cognito_stack)
ecs_stack.add_dependency(vpc_stack)

# ── cdk-nag (opt-in via CDK_NAG=1 env var) ─────────────────────────────────
if os.environ.get("CDK_NAG", "").strip() in ("1", "true", "yes"):
    from cdk_nag import AwsSolutionsChecks

    cdk.Aspects.of(app).add(AwsSolutionsChecks(verbose=True))

app.synth()
