#!/usr/bin/env bash
# Generate ui/.env from CDK stack outputs after deploying MediaContractsCognito.
#
# Run this after deploying the Cognito stack and before building the UI image.
# The generated .env is baked into the Vite bundle at build time.
#
# Usage:
#   DEPLOYMENT_ID=dev ./deployment/scripts/generate_ui_env.sh
#   DEPLOYMENT_ID=dev ECS_SERVICE_URL=https://xxx.elb.amazonaws.com ./deployment/scripts/generate_ui_env.sh

set -euo pipefail

DEPLOYMENT_ID="${DEPLOYMENT_ID:-dev}"
AWS_REGION="${AWS_REGION:-us-west-2}"

# Stack name — reads from STACK_SUFFIX env var (set by deploy.sh)
if [ -n "${STACK_SUFFIX:-}" ]; then
  STACK_NAME="MC-Cognito-${STACK_SUFFIX}"
else
  # Fall back to state file
  STATE_FILE=".deploy-state-${DEPLOYMENT_ID}.json"
  if [ -f "${STATE_FILE}" ]; then
    _suffix=$(python3 -c "import json; print(json.load(open('${STATE_FILE}')).get('stack_suffix', ''))" 2>/dev/null || echo "")
    if [ -n "$_suffix" ]; then
      STACK_NAME="MC-Cognito-${_suffix}"
    fi
  fi
fi

if [ -z "${STACK_NAME:-}" ]; then
  echo "ERROR: Could not determine Cognito stack name. Set STACK_SUFFIX or ensure .deploy-state-${DEPLOYMENT_ID}.json exists."
  exit 1
fi

# ECS service URL — set this to your ALB/ECS Express URL after first deploy
# Used for Cognito callback and logout URLs in the Vite bundle
ECS_SERVICE_URL="${ECS_SERVICE_URL:-http://localhost:7870}"

echo "==> Reading Cognito outputs from ${STACK_NAME}..."

get_output() {
    aws cloudformation describe-stacks \
        --stack-name "${STACK_NAME}" \
        --region "${AWS_REGION}" \
        --query "Stacks[0].Outputs[?OutputKey=='${1}'].OutputValue" \
        --output text
}

AUTHORITY=$(get_output "Authority")
UI_CLIENT_ID=$(get_output "UIClientId")
COGNITO_DOMAIN=$(get_output "CognitoDomain")

if [ -z "${AUTHORITY}" ] || [ -z "${UI_CLIENT_ID}" ]; then
    echo "ERROR: Could not read Cognito outputs. Is ${STACK_NAME} deployed?"
    exit 1
fi

ENV_FILE="ui/.env"

cat > "${ENV_FILE}" << EOF
# Auto-generated by deployment/scripts/generate_ui_env.sh
# Re-run after deploying MediaContractsCognito or changing ECS_SERVICE_URL

# Cognito OIDC (baked into Vite bundle at build time)
VITE_COGNITO_AUTHORITY=${AUTHORITY}
VITE_COGNITO_CLIENT_ID=${UI_CLIENT_ID}
VITE_COGNITO_DOMAIN=${COGNITO_DOMAIN}
EOF

echo "✓ Written to ${ENV_FILE}"
echo ""
echo "Next steps:"
echo "  1. Build the UI image:  docker build --platform linux/amd64 -t media-contracts ."
echo "  2. Push to ECR:         ./deploy_ecs_update.sh"
echo ""
echo "If this is a new ECS deployment, set ECS_SERVICE_URL to your ALB URL"
echo "and re-run this script, then rebuild and redeploy."
